### ISSUE TITLE
Compiling on macOS

### ISSUE THREAD

**Issue by lhilbert** [lhilbert/active-microemulsion#1]
When compiling on macOS by make, it seems we are being directed to clang, which then gives linking errors.

Then we got gcc via homebrew, and forced in the make file to look for the "real" gcc in the Cellar directory of homebrew. Now we seem to be getting a type error, for a type that is not present on macOS.

make error report:

```
lhilberprivate2:active-microemulsion hilbert$ make
/usr/local/Cellar/gcc/8.2.0/bin/g++-8 -c -std=c++14 -O2 -Wall -pedantic -Werror src/main.cpp -o src/main.o -lboost_program_options -lboost_system -lboost_filesystem -lm
/usr/local/Cellar/gcc/8.2.0/bin/g++-8 -c -std=c++14 -O2 -Wall -pedantic -Werror src/Timing.cpp -o src/Timing.o -lboost_program_options -lboost_system -lboost_filesystem -lm
src/Timing.cpp:5:10: fatal error: bits/types/struct_timeval.h: No such file or directory
 #include <bits/types/struct_timeval.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [src/Timing.o] Error 1
```

**Comment by churli** [comment]
Issue was reproduced by building with the `clang` compiler and was caused by a wrong include.
This has been fixed and now I am able build with clang, through cmake.
