### ISSUE TITLE
Instructions how to build and run on SCC (or other) cluster

### ISSUE THREAD

**Issue by lhilbert** [lhilbert/active-microemulsion#22]
We need a step-by-step guide how the simulations can be run on the SCC bwUniCluster, or another computing cluster. Or is this hidden somewhere? The first readme should take us there. Also, we have to make sure all outdated info is removed from that page.

**Comment by lhilbert** [comment]
After finding the building instructions, I tried with ./cmake-with-icc.sh

This gives different errors with different versions of boost loaded.

**Comment by churli** [comment]
I started writing [this step-by-step tutorial](https://github.com/lhilbert/active-microemulsion/blob/master/documentation/tutorial.md) for how to build and run on BwUniCluster starting from scratch (i.e. repo clone included).

There was a bug in the cmake build process when building in `Release` mode: it assumed PGO had been performed already and it was therefore failing to build if no profile was found.
Now PGO can be selected with a specific cmake variable (see `cmake-with-icc.sh` for how to use it) and `Release` mode can be selected also at the first build.

So now the build works from a just-cloned repository and without requiring any change in the build script.
