### ISSUE TITLE
Build with make: dependency not found

### ISSUE THREAD

**Issue by lhilbert** [lhilbert/active-microemulsion#23]
The following comes up as an error message using the make command

It says pcg_random.hpp cannot be located.

###################

In Datei, eingebunden von src/Grid/Grid.h:14,
                 von src/main.cpp:3:
src/Grid/../Utils/RandomGenerator.h:14:10: schwerwiegender Fehler: pcg_random.hpp: Datei oder Verzeichnis nicht gefunden
   14 | #include <pcg_random.hpp>
      |          ^~~~~~~~~~~~~~~~
Kompilierung beendet.
make: *** [src/main.o] Error 1

**Comment by churli** [comment]
Makefile is not updated and therefore it is expected not to be able to build the current version of the code.
I removed any mention of building with `make` from the documentation to avoid any further confusion.
Support for building with `make` will be probably discontinued.
