### ISSUE TITLE
Hick ups during setup and execution on bwUniCluster

### ISSUE THREAD

**Issue by lhilbert** [lhilbert/active-microemulsion#24]
Mostly stuff that's not in the documentation:
- module load python3
- change rights on the files needed for scheduling, from /utils; they are not permitted to ... by default
- change dryRun to True in the call in the pythin script

**Comment by lhilbert** [comment]
I am getting an error and crash because files are missing, specifically

/scratch/slurm_tmpdir/Job_17187954/[redacted]/job_29339/active-microemulsion

I suspect it is because somewhere in the scheduling scripts a directory is hard-coded, but my directory structure is different.

This seems to be one candidate in the Moab-job.sh file, for example:

# Settings for config data and shared libraries
REPO_BASE_DIR=${HOME}/Repo/active-microemulsion
REPO_ITEMS_TO_COPY=( "active-microemulsion" "cmake-build-*" "lib" "ChainConfigs" "utils" ) # Will be copied with "cp -r"

**Comment by lhilbert** [comment]
To continue the diagnosis of the problem, it seems that the call to the executable goes to a directory $scratch that does either not exist, or the executable file active-microemulsion is not there.

Next step: trace back how $scratch is assembled as a path, and if that very directory is actually generated and populated with the required files before the call to the executable.

**Comment by lhilbert** [comment]
Going further: it seems the directory path is fine, but there might be a problem getting the actual executable copied there. Could it be that compiling with icc instead of regular "make" puts it in a different location?!

**Comment by lhilbert** [comment]
We're getting somewhere. The active-microemulsion "file" is actually a link, and that goes back to the user home directory, which the node cannot access.

The solution could be to replace this link with the actual executable from the icc build?!

**Comment by lhilbert** [comment]
Now the jobs complete without error report, but finish after 1.5 seconds with no output from the simulation. Also, had to use chmod -R a+rwx on the active-microemulsion directory again after copying over the executable.

**Comment by lhilbert** [comment]
When executing ./active-microemulsion with the generated.chains and arguments for the runSimulationSet.py locally on the node, it produces a memory error and stops. So seems to be an issue with the executable itself. @churli

**Comment by churli** [comment]
This was actually caused by a combination of bugs (and missing documentation).
The bugs have all been solved as of commit cc170fe8df4e65d07474d4b537763d1d299c0b4d .
One problem that has a workaround but anyway needs to be eventually solved is now moved to issue #25.
Updates to documentation are coming shortly.
