### ISSUE TITLE
Hard-coded occurrencesof flavopiridol flag?

### ISSUE THREAD

**Issue by lhilbert** [lhilbert/active-microemulsion#28]
In the commands used for scheduling on bwUniCluster, it seems there are some occurrences of hard-coded flavopiridol flags. Does this make sense?

https://github.com/lhilbert/active-microemulsion/blob/3a7b37f403af73d8c9b4d81d2f8ea87213f69455/utils/BwUniClusterScripts/schedulingLib.py#L249

**Comment by churli** [comment]
Yes, this is expected and necessary for executing the simulations in the way we need.

If no event flag is passed, the simulation start by default by using the rates specified from the command line. That is, the simulation starts in an "active" state.

However in our simulations we need the system to initially relax for a certain amount of time (10m) before an activation event is called.
The way we implement this initial relaxation is by disabling the rates at time 0 (i.e. by calling `--flavopiridol 0`) and then calling `--activate` at the time we want the system to start with trascription.
