### ISSUE TITLE
Unclear what is meant by "copy libiomp5.so" locally

### ISSUE THREAD

**Issue by lhilbert** [lhilbert/active-microemulsion#30]
I could find out where to copy the library file from. But not where to, if you say "you may need to copy the libiomp5.so lib locally". Where do I copy it to?

**Comment by churli** [comment]
Thanks for asking and reporting this unclear documentation bit.
With commits 6970112374fed233b771cd2118bbf4f7083e1cc1 and a4f3827a819180f4591cf6c9bbfe882d33923b9c it should now be clearer and automated.

Basically the library has to be linked/copied to the lib/ subfolder in the repository.
