### ISSUE TITLE
Spatial anisotropy in simulation results

### ISSUE THREAD

**Issue by lhilbert** [lhilbert/active-microemulsion#31]
In basically all simulation results, there's a bias towards chromatin touching the left and bottom edge more than the top and right. This could be due to (a) an anisotropy in how swaps are carried out, or (b) problems during export of data for saving, so that the top and right lanes of the simulation are not written to the output.

**Comment by churli** [comment]
There doesn't seem to be any frame-offset problem when writing the output, as we can clearly see that the initial chromatin layout is properly displayed on output files.

**Comment by lhilbert** [comment]
So, as the phenomenon occurs most visibly at edges, it is maybe related to swap operations at the edges.

**Comment by lhilbert** [comment]
Found that the function isSwapBlockedByStickyBoundary(x, y, nx, ny) was addressed as isSwapBlockedByStickyBoundary(x, y, 0, 0) in Microemulsion.cpp

This had the effect that the target site of a given swap was not considered. Instead somehow only the current site was considered.

In addition, when the flag --no-sticky-boundary was used, no more bias was seen in the simulations. This flag gets rid of the effect of the sticky boundary function mentioned above, so it seems this was the course of the anisotropy.
